### PR TITLE
Added new exception for Strangers 2018, TVDB_ID 351028.

### PR DESCRIPTION
**Pull request by VeNoMouS**

### CODE REVIEW

**Comment by thezoggy** [comment]
https://forums.thetvdb.com/viewtopic.php?f=7&t=51115

**Comment by VeNoMouS** [comment]
@thezoggy hrrrm you sure, i had to add that exception because couple episodes released with and without.. tvdb didnt have year on title...

**Comment by VeNoMouS** [comment]
It failed to pick up the year ones till i added it in...

**Comment by VeNoMouS** [comment]
Ah.. your links makes sense... I only added it this morning.. and it didnt have the year..

**Comment by VeNoMouS** [comment]
TVDB's api still giving it at out `Maniac` not `Maniac 2018`

**Comment by thezoggy** [comment]
Looks like tvdb admin updated show name

**Comment by VeNoMouS** [comment]
@thezoggy yup confirmed, you want me to remove that PR?

**Pull request merged**
