### PR TITLE
QoQ fix

### PR DESCRIPTION
**Pull request by bruvv**
Example for the walking dead:
http://ftdworld.net/spotinfo.php?id=955314
TITLE: THE WALKING DEAD (2013)

Example for continuum:
http://ftdworld.net/spotinfo.php?id=984538
TITLE: Continuum (2013)

### CODE REVIEW

**Comment by thezoggy** [comment]
im still in china for a few days, ill check on this when i'm back in town

**Comment by bruvv** [comment]
np @thezoggy enjoy your stay!

**Comment by thezoggy** [comment]
havent forgotten about you, talking to midgetspy about this.

**Comment by bruvv** [comment]
NP man we have our own fork zo no rush
Op 29 sep. 2013 16:13 schreef "thezoggy" notifications@github.com het
volgende:

**Comment by bruvv** [comment]
might be better if I add a new PR ?

**Comment by bruvv** [comment]
bump

**Comment by bruvv** [comment]
bump @thezoggy @midgetspy  this is keeping updated and updated... but why not add this fix for our dutch peoples?

**Comment by thezoggy** [comment]
sadly midgetspy hasn't been around for me to talk to him about the whole QoQ thing. I'll have to bring this up with itofzo instead since he's gotten access to push changes.

**Comment by bruvv** [comment]
I don't get it. it's just a simple fix which will save so many hassle. It's just how to write down their stuff. (they use the year after the name, which sickbeard is not reconizing since it can't handle the year after the name).

So it's just what you have been adding for other people who use different names.

**Comment by bruvv** [comment]
I'll make a new PR, a clean one.

**Pull request closed without merging**
